// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// EstAllModels
List EstAllModels(arma::mat X, arma::mat Xnew, arma::mat y, arma::mat s);
RcppExport SEXP FMA_EstAllModels(SEXP XSEXP, SEXP XnewSEXP, SEXP ySEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xnew(XnewSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type s(sSEXP);
    __result = Rcpp::wrap(EstAllModels(X, Xnew, y, s));
    return __result;
END_RCPP
}
