# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EstAllModels <- function(X, Xnew, y, s) {
    .Call('FMA_EstAllModels', PACKAGE = 'FMA', X, Xnew, y, s)
}

